feat(estrutura): conexão com o banco de dados
mdsreq-fga-unb/2023.2-NutriPlanner pull request #63
Opened 2023-11-28 01:45 UTC by LucasSpinosa

## Descrição
Realiza a conexão com o banco de dados MongoDB do Atlas.

## Verificação (DoD)

Não aplicável

## Observações

Para testar a conexão, edite o arquivo ".env" com os dados do canal 'dados-env' no servidor do Discord.

Após isso, rode 'npm run dev'.

2023-11-28 01:58 UTC, MatsFidelis approved these changes
Alterações verificadas e testadas. Envio de email concluído e conexão do banco funcional.

2023-11-30 03:36 UTC, MillenaQueiroz approved these changes
lgtm

2023-12-01 16:06 UTC, arthurgrandao requested changes
Troca a url de conexão para:

`mongodb+srv://${DB_USER}:${DB_PASSWORD}@nutriplanner.uja7pbr.mongodb.net/NutriPlanner?retryWrites=true&w=majority`

Pois assim o nome da base de dados fica especificado como 'NutriPlanner'

2023-12-01 17:49 UTC, MatsFidelis commented
> Troca a url de conexão para:
> 
> `mongodb+srv://${DB_USER}:${DB_PASSWORD}@nutriplanner.uja7pbr.mongodb.net/NutriPlanner?retryWrites=true&w=majority`
> 
> Pois assim o nome da base de dados fica especificado como 'NutriPlanner'

Feito a troca do link !!

2023-12-01 18:00 UTC, arthurgrandao approved these changes
show

2023-12-01 18:06 UTC, merged